---
galaxy_info:
  role_name: cis_l2
  author: tabyaos
  description: CIS Amazon Linux 2023 Benchmark Level 2 hardening for Kubernetes worker nodes
  license: BSL-1.1
  min_ansible_version: "2.14"
  platforms:
    - name: Amazon
      versions:
        - "2023"
  galaxy_tags:
    - security
    - hardening
    - cis
    - kubernetes

dependencies: []
