#!/usr/bin/env python3
"""
TabyaOS compliance doc generator.

Reads compliance/control-mappings.yaml and generates:
  - compliance/generated/by-framework/<framework>.md   — one file per framework
  - compliance/generated/by-role/<role>.md             — one file per Ansible role
  - compliance/generated/coverage-summary.md           — cross-framework coverage table

Usage:
  python3 scripts/gen-compliance-docs.py [--mappings compliance/control-mappings.yaml]
                                          [--output-dir compliance/generated]
"""

import argparse
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required — pip install pyyaml", file=sys.stderr)
    sys.exit(1)


FRAMEWORK_NAMES = {
    "CIS_AL2023_L2": "CIS Amazon Linux 2023 Benchmark Level 2",
    "CIS_K8s_v1.8": "CIS Kubernetes Benchmark v1.8",
    "PCI_DSS_v4.0": "PCI-DSS v4.0",
    "SOC2_TSC": "SOC 2 Trust Service Criteria",
    "NIST_800-53_Rev5": "NIST SP 800-53 Rev 5",
}


def load_mappings(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path}")


def fmt_reqs(reqs) -> str:
    if isinstance(reqs, list):
        return ", ".join(str(r) for r in reqs)
    return str(reqs)


def gen_by_framework(controls: list, frameworks: list, out_dir: Path) -> None:
    for fw in frameworks:
        fw_controls = [c for c in controls if fw in c.get("frameworks", {})]
        if not fw_controls:
            continue

        name = FRAMEWORK_NAMES.get(fw, fw)
        lines = [
            f"# {name} — TabyaOS Control Coverage",
            "",
            f"> Generated by `scripts/gen-compliance-docs.py` on {date.today()}",
            "",
            f"**{len(fw_controls)} controls** mapped to {fw}.",
            "",
            "| Control ID | Title | Role | Requirements |",
            "|-----------|-------|------|-------------|",
        ]
        for c in sorted(fw_controls, key=lambda x: x["id"]):
            reqs = fmt_reqs(c["frameworks"][fw])
            lines.append(
                f"| {c['id']} | {c['title']} | `{c['ansible_role']}` | {reqs} |"
            )

        lines += [
            "",
            "## Control Details",
            "",
        ]
        for c in sorted(fw_controls, key=lambda x: x["id"]):
            reqs = fmt_reqs(c["frameworks"][fw])
            all_fw = ", ".join(
                f"**{f}**: {fmt_reqs(r)}" for f, r in c.get("frameworks", {}).items()
            )
            lines += [
                f"### {c['id']} — {c['title']}",
                "",
                f"- **Role:** `{c['ansible_role']}`",
                f"- **Task file:** `{c['ansible_task']}`",
                f"- **{fw} requirements:** {reqs}",
                f"- **All frameworks:** {all_fw}",
                "",
            ]

        write_file(out_dir / "by-framework" / f"{fw}.md", "\n".join(lines))


def gen_by_role(controls: list, out_dir: Path) -> None:
    by_role: dict = defaultdict(list)
    for c in controls:
        by_role[c["ansible_role"]].append(c)

    for role, role_controls in sorted(by_role.items()):
        lines = [
            f"# Ansible Role: `{role}` — Compliance Coverage",
            "",
            f"> Generated by `scripts/gen-compliance-docs.py` on {date.today()}",
            "",
            f"**{len(role_controls)} controls** implemented by this role.",
            "",
            "| Control ID | Title | Frameworks |",
            "|-----------|-------|-----------|",
        ]
        for c in sorted(role_controls, key=lambda x: x["id"]):
            fw_list = ", ".join(c.get("frameworks", {}).keys())
            lines.append(f"| {c['id']} | {c['title']} | {fw_list} |")

        lines += ["", "## Control Details", ""]
        for c in sorted(role_controls, key=lambda x: x["id"]):
            all_fw = "; ".join(
                f"**{f}**: {fmt_reqs(r)}" for f, r in c.get("frameworks", {}).items()
            )
            lines += [
                f"### {c['id']} — {c['title']}",
                "",
                f"- **Task file:** `{c['ansible_task']}`",
                f"- **Framework requirements:** {all_fw}",
                "",
            ]

        write_file(out_dir / "by-role" / f"{role}.md", "\n".join(lines))


def gen_summary(controls: list, frameworks: list, out_dir: Path) -> None:
    header = ["# TabyaOS Compliance Coverage Summary", "",
              f"> Generated {date.today()} — {len(controls)} total controls", "",
              "## Coverage by Framework", ""]

    fw_cols = " | ".join(f for f in frameworks)
    header_row = f"| Control ID | Title | {fw_cols} |"
    sep_row = "|" + "---|" * (2 + len(frameworks))
    header += [header_row, sep_row]

    for c in sorted(controls, key=lambda x: x["id"]):
        cells = []
        for fw in frameworks:
            if fw in c.get("frameworks", {}):
                reqs = c["frameworks"][fw]
                req_str = fmt_reqs(reqs)
                cells.append(f"✓ {req_str}")
            else:
                cells.append("—")
        cell_str = " | ".join(cells)
        header.append(f"| {c['id']} | {c['title']} | {cell_str} |")

    header += ["", "## Controls by Role", ""]
    by_role: dict = defaultdict(list)
    for c in controls:
        by_role[c["ansible_role"]].append(c["id"])
    for role, ids in sorted(by_role.items()):
        header.append(f"- **`{role}`**: {', '.join(sorted(ids))}")

    header += ["", "## Framework Requirement Counts", ""]
    for fw in frameworks:
        fw_controls = [c for c in controls if fw in c.get("frameworks", {})]
        all_reqs: set = set()
        for c in fw_controls:
            reqs = c["frameworks"][fw]
            if isinstance(reqs, list):
                all_reqs.update(str(r) for r in reqs)
            else:
                all_reqs.add(str(reqs))
        name = FRAMEWORK_NAMES.get(fw, fw)
        header.append(f"- **{name}**: {len(fw_controls)} controls covering {len(all_reqs)} requirement IDs")

    write_file(out_dir / "coverage-summary.md", "\n".join(header))


def main():
    parser = argparse.ArgumentParser(description="Generate TabyaOS compliance docs")
    parser.add_argument(
        "--mappings",
        default="compliance/control-mappings.yaml",
        help="Path to control-mappings.yaml",
    )
    parser.add_argument(
        "--output-dir",
        default="compliance/generated",
        help="Output directory for generated docs",
    )
    args = parser.parse_args()

    mappings_path = Path(args.mappings)
    out_dir = Path(args.output_dir)

    if not mappings_path.exists():
        print(f"ERROR: {mappings_path} not found", file=sys.stderr)
        sys.exit(1)

    data = load_mappings(mappings_path)
    controls = data.get("controls", [])
    frameworks = data.get("frameworks", [])

    print(f"Loaded {len(controls)} controls across {len(frameworks)} frameworks")

    gen_by_framework(controls, frameworks, out_dir)
    gen_by_role(controls, out_dir)
    gen_summary(controls, frameworks, out_dir)

    print(f"\nDone — {out_dir}/")


if __name__ == "__main__":
    main()
