---
# CIS Red Hat Enterprise Linux 9 Benchmark Level 2

- name: "CIS RHEL9 | Section 1 — Filesystem Configuration"
  ansible.builtin.import_tasks: 1_filesystem.yml
  tags: [cis_rhel9, cis_rhel9_filesystem]

- name: "CIS RHEL9 | Section 2 — Services"
  ansible.builtin.import_tasks: 2_services.yml
  tags: [cis_rhel9, cis_rhel9_services]

- name: "CIS RHEL9 | Section 3 — Network Configuration"
  ansible.builtin.import_tasks: 3_network.yml
  tags: [cis_rhel9, cis_rhel9_network]

- name: "CIS RHEL9 | Section 4 — Logging and Auditing"
  ansible.builtin.import_tasks: 4_logging.yml
  tags: [cis_rhel9, cis_rhel9_logging]

- name: "CIS RHEL9 | Section 5 — Access, Authentication and Authorization"
  ansible.builtin.import_tasks: 5_access.yml
  tags: [cis_rhel9, cis_rhel9_access]

- name: "CIS RHEL9 | Section 6 — System Maintenance"
  ansible.builtin.import_tasks: 6_maintenance.yml
  tags: [cis_rhel9, cis_rhel9_maintenance]
